import { Geist, Geist_Mono } from "next/font/google";
import ProtectedRoute from "./ProtectedRoute";
import "./globals.css";
import { UserContextProvider } from "@/context/UserContext";
import AppShell from "./AppShell";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <UserContextProvider>
          <ProtectedRoute>
            <AppShell>
              {children}
            </AppShell>
          </ProtectedRoute>
        </UserContextProvider>
      </body>
    </html>
  );
}

